# Generated by Django 3.0.3 on 2020-02-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('club', models.TextField(max_length=200)),
                ('fr', models.FloatField()),
                ('bu', models.FloatField()),
                ('ba', models.FloatField()),
                ('br', models.FloatField()),
            ],
        ),
    ]
