# Generated by Django 3.0.3 on 2020-02-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swim',
            name='img',
            field=models.TextField(max_length=4086, null=True),
        ),
    ]
